### ISSUE TITLE
Not Found  The requested URL /YouPHPTube/.... was not found on this server.

### ISSUE THREAD

**Issue by zoespace** [DanielnetoDotCom/YouPHPTube#763] opened 2018-06-11 18:38 UTC
After installation, most of the link such as Login, Contact, Channels, etc gives me this error 
"Not Found
The requested URL /YouPHPTube/......  was not found on this server."
Please how do I rectify this error please?

**Comment by Nisarg22** [comment] 2018-06-11 18:39
I also have same problem they are checking

**Comment by DanielnetoDotCom** [comment] 2018-06-11 18:40
Hi, we just sent a bunch of fixes including channels, charts and more.
can you please update your files and check again?

please update us if it works

**Comment by Nisarg22** [comment] 2018-06-11 18:40
Same error also comes if u delete your site completely and re install it from 0 it will not even load installation page directory

**Comment by DanielnetoDotCom** [comment] 2018-06-11 18:41
I will check now a clean installation

**Comment by DanielnetoDotCom** [comment] 2018-06-11 18:48
I found an issue and sent a fix, please try again

**Comment by Nisarg22** [comment] 2018-06-11 18:51
Wait I m checking

**Comment by Nisarg22** [comment] 2018-06-11 19:01
Captcha in contact page not showing rest everything is solved

**Comment by DanielnetoDotCom** [comment] 2018-06-11 19:01
It was fixed after this update
please update again

**Comment by DanielnetoDotCom** [comment] 2018-06-11 19:02
Really apologize for that

**Comment by Nisarg22** [comment] 2018-06-11 19:02
Even in advanced configuration page

**Comment by Nisarg22** [comment] 2018-06-11 19:02
No problem

**Comment by DanielnetoDotCom** [comment] 2018-06-11 19:07
@Nisarg22 is it back to work for you?

**Comment by Nisarg22** [comment] 2018-06-11 19:17
Done

**Comment by Nisarg22** [comment] 2018-06-11 19:17
Great work

**Comment by Nisarg22** [comment] 2018-06-11 19:21
![screenshot_20180612-005028](https://user-images.githubusercontent.com/39002772/41252415-af36d33c-6dda-11e8-8f61-e02099417982.jpg)
My channel page

**Comment by hersche** [comment] 2018-06-11 19:27
was not able to reproduce this on desktop, but i have to get this on the phone as i see (have to charge). how does it react with a video / not empty?

when you restore your backup, please clear the videos/cache-folder, because a lot of javascript has changed..

**Comment by zoespace** [comment] 2018-06-11 19:32
After another clean installation, same errors

![screenshot-140 82 12 112-2018-06-11-20-33-24](https://user-images.githubusercontent.com/40180408/41252866-5cb39092-6db6-11e8-95e2-ce04c2eae3a4.png)

**Comment by hersche** [comment] 2018-06-11 19:37
ok, but 404 look like a setup-problem (which is caused of my fail)..

the file ".htaccess" is often a hidden file, may it's missing?

if yes, you can simply rename "classic.htaccess" to ".htaccess". 

before, you had a message about activating rewrite aka your .htaccess is missing.. this message is gone for the moment, if this is confusing.

**Comment by DanielnetoDotCom** [comment] 2018-06-11 19:37
Hi

I just test it locally and on demo site and it is working fine

**Comment by zoespace** [comment] 2018-06-11 19:46
I think you are are correct hersche. But the .htaccess" file is present. My server is probably not reading it. Any suggestions on how to fix this?

**Comment by hersche** [comment] 2018-06-11 19:50
hehe, as you wrote the comment, i pushed the classic "error"/manual for this again, so there you would find, how it works again..

but i will put this quick in the wiki, so it's also independed and you will be able to see it

**Comment by Nisarg22** [comment] 2018-06-11 19:53
Please update my channel page

**Comment by hersche** [comment] 2018-06-11 19:54
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Message-when-rewrite-is-not-set

**Comment by Nisarg22** [comment] 2018-06-11 19:56
Check screen shot I uploaded the problem is with design it does not show my channel name

**Comment by hersche** [comment] 2018-06-11 19:58
> Please update my channel page
i have it in mind, but does it look same with a video?

also my phone is on charging atm, but we will get that soon i think..

**Comment by zoespace** [comment] 2018-06-11 20:09
Thanks a lot, hersche. I followed the link and the instructions there. It's working now.

**Comment by hersche** [comment] 2018-06-12 09:55
@Nisarg22 can you confirm, the mobile-view is working now? any other bad effects by restructering?

**Comment by hersche** [comment] 2018-06-13 23:37
the title is fixed, even the mobile-view (basicly tested), but no feedback, so i close it. if the mobile problem persists, open a new issue please.

**Closed by hersche** 2018-06-13 23:37 UTC

**Comment by kweibel** [comment] 2019-02-10 21:16
Hello I just installed YouPHPTube for my son and I got this error The requested URL /YouPHPTube/user was not found on this server.
Ubuntu 16.04 
I fowled the install guide still get errors whenever I click on a link.

**Comment by DanielnetoDotCom** [comment] 2019-02-11 14:27
maybe you are missing the mod rewrite

**Comment by KennanObura** [comment] 2019-12-10 12:47
Hi. i also have the same error on two clean installations. 
My mod_rewrite is enabled and i have aswell renamed classic.htaccess to .htaccess. What could be the reason? Could it be that my url looks like this http://hostname/YouPHPTube? I think my .htaccess is not read

**Comment by DanielnetoDotCom** [comment] 2019-12-10 13:09
try to not rename the .htaccess, keep the default one

also take a screenshot and check your log file

**Comment by KennanObura** [comment] 2019-12-10 13:30
![image](https://user-images.githubusercontent.com/8361376/70533495-449f5f00-1b6a-11ea-9d2b-0cc361aaf579.png)
This happens when i leave classic.htaccess as it is

**Comment by DanielnetoDotCom** [comment] 2019-12-10 13:33
this is the mod-rewrite for sure

I am not sure how you are configuring it, but you are missing something

**Comment by KennanObura** [comment] 2019-12-10 13:35
Well. When i run phpInfo() it is enabled
![image](https://user-images.githubusercontent.com/8361376/70533936-1cfcc680-1b6b-11ea-9dd3-76a4316cd73d.png)
And this is the log

**Comment by DanielnetoDotCom** [comment] 2019-12-10 13:38
I am really not sure, the only thing I can tell you is for you to look your mod rewrite

what Operational system are you using?

**Comment by KennanObura** [comment] 2019-12-10 13:38
![image](https://user-images.githubusercontent.com/8361376/70534155-7e249a00-1b6b-11ea-9217-e24b69178e0f.png)

**Comment by KennanObura** [comment] 2019-12-10 13:38
Am using ubuntu 19

**Comment by DanielnetoDotCom** [comment] 2019-12-10 13:49
I have never had a mod rewrite problem on Ubuntu 19. but there are problems to compile nginx with the RTMP on this version

I recomend you go to ubuntu 18.04

also make sure you run this 

`sudo a2enmod rewrite`

change the apache2.conf file with the instructions on the first page, and make sure you restart the apache

**Comment by KennanObura** [comment] 2019-12-10 13:52
![image](https://user-images.githubusercontent.com/8361376/70534840-f8095300-1b6c-11ea-9cb6-e6c3b3400b66.png)
 I cant seem to understand why i cant get this working. 
When i leave classic.htaccess unrenamed i get  this
![image](https://user-images.githubusercontent.com/8361376/70534971-356de080-1b6d-11ea-956b-69637fab7fe0.png)
When i rename it my routes seem broken. Pages not found

**Comment by DanielnetoDotCom** [comment] 2019-12-10 13:53
did you restart apache?

**Comment by KennanObura** [comment] 2019-12-10 13:53
Yap. Restarted severally .
And I dont think going back to Ubuntu 18.04 can solve the issue. Or why would you recommend that?

**Comment by DanielnetoDotCom** [comment] 2019-12-10 14:05
Ubuntu 19 is not Long-term support (LTS) you will lose support for that version next year in the best case
Ubuntu 16 or 18 are LTS

https://wiki.ubuntu.com/Releases

![image](https://user-images.githubusercontent.com/18009293/70536129-f1fb7e00-1b3c-11ea-85ae-45adb3b025f9.png)


you have some misconfiguration somewhere in your apache, I do not know where.

Mod rewrite is not a problem on ubuntu 19

**Comment by KennanObura** [comment] 2019-12-10 14:11
Ok. Maybe i completely remove apache and install it a fresh see if it works. Thanks

**Comment by DanielnetoDotCom** [comment] 2019-12-10 14:23
you should go to Ubuntu 18.04

**Comment by KennanObura** [comment] 2019-12-11 11:43
Hi. I did a clean 18.04 installation. Have mod_rewrite enabled but still i get broken pages 
![image](https://user-images.githubusercontent.com/8361376/70618748-a2907d00-1c24-11ea-9dd2-32143d293acd.png)

**Comment by KennanObura** [comment] 2019-12-11 12:12
I just did configure apache with "   AllowOverride All" instead and all seems ok now.

**Comment by DanielnetoDotCom** [comment] 2019-12-11 14:18
thanks for the update
