### ISSUE TITLE
Embed video  Direct video-link (mp4)

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#753] opened 2018-06-08 09:11 UTC
Error showing i try to google drive and youtube, openload.co but same error showing.

The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by hersche** [comment] 2018-06-08 10:59
> Direct video-link (mp4)

it's in your title!

a google-drive-link is NOT DIRECT

openload is NOT DIRECT

those sites have a own player, own apis, etc. NOTHING THERE IS DIRECT!

Direct link means: Somewhere is installed a apache, apache use no software but has MP4-files. so you can take that DIRECT link and embed it there.

for openload for example, maybe EMBEDED video works, maybe not supportet.

if you want to use openload, then first download the mp4, upload it somewhere to a apache or similiar and take that link.

we have in mind to do a google-drive-plugin, but because this is not direct, we need to handle this via the google-api and anyway not as direct-link!

is this question answered for you? 

that's not a bug, just another way of think how that function can be used. i hope i was able to clarify that.

**Comment by hersche** [comment] 2018-06-08 16:31
this is what i mean:

https://raw.githubusercontent.com/youtube/api-samples/master/java/src/main/resources/sample-video.mp4

ending with .mp4 is not always the case, but the inserted url should only have the browsers mediaplayer or ask you for download the mp4-file (most, just will play it).

have a look and/or try to include that video for test.

**Comment by hersche** [comment] 2018-06-09 01:08
i try to document this here: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/User-manual
will be extended soon..

**Comment by gujarraju** [comment] 2018-06-09 09:53
thanks man know working fine i copied download link that one working but youtube download link lenth big not short

**Comment by hersche** [comment] 2018-06-09 20:49
> but youtube download link lenth big not short

Not shure what you mean with this..

For youtube, i highly recommend the embeded-type..

Does it finaly completly work or can you give a example about the short/bug-links?

**Comment by hersche** [comment] 2018-06-11 08:39
> thanks man know working fine
well, then i can close it, i think..

**Closed by hersche** 2018-06-11 08:39 UTC
