### ISSUE TITLE
Not Mobile Friendly

### ISSUE THREAD

**Issue by CharlesChidozie** [DanielnetoDotCom/YouPHPTube#833] opened 2018-07-05 23:25 UTC
The Home Page and some other pages like /mvideos are not responsive. It seems the page is extra-wide

**Comment by DanielnetoDotCom** [comment] 2018-07-05 23:39
Agree with you, some admin pages are not mobile friendly, but the main pages for final users those are mobile friendly

**Comment by CharlesChidozie** [comment] 2018-07-05 23:43
Any Solution for this? Where can i locate the Page Width for adjustment?

**Comment by DanielnetoDotCom** [comment] 2018-07-05 23:53
I think most of the problem is on the bootgrid, I want to move all to the datatable add on, but even with datatable I dont think it will be fixed, there are many columns to display, a mobile cant handle it

**Comment by CharlesChidozie** [comment] 2018-07-06 00:05
OK.

**Closed** 2019-02-21 17:24 UTC
Labels: wontfix
