### ISSUE TITLE
After finishing installing everything and deleting the 'install' folder, it still goes to the error page.

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube#739] opened 2018-06-04 18:44 UTC
Hi, I have followed all your steps to install the YouPHPTube. But after finishing every step and also deleting the 'install' folder, when I go to my website, the error page still occurs. What should I do to fix it? Thanks!
Here is my website: http://45.77.130.186/.
And I think this may be the reason: I put all the files inside **/var/www/html** instead of **/var/www/html/YouPHPTube**. I just moved these files. If this is the problem, then how should I fix it? If not, then what it the problem?

**Comment by hersche** [comment] 2018-06-04 19:20
the info i see is about setup apache correct.. so you have to change your webserver like it's written there.

**Comment by VictorLi0213** [comment] 2018-06-04 21:01
I have done what the error page asked me to do.
And what do you mean the videos/configuration.php? What is that?

**Comment by VictorLi0213** [comment] 2018-06-04 21:08
What do I need to change in videos/configuration.php?

**Comment by DanielnetoDotCom** [comment] 2018-06-04 21:11
Hi

The error is regarding the modrewrite.
Please make sure it is enabled

**Comment by VictorLi0213** [comment] 2018-06-04 21:33
Hi, thank you for your reply. I think I made some problems. Just now I started a new server and did everything again. But here is another problem: I have changed the file apache2.conf as what the website said. But after I refresh the page, the error page is still there. Here is the website: http://45.32.33.209/. Thanks!

**Comment by VictorLi0213** [comment] 2018-06-04 21:35
There is one thing that I want to mention: I moved all the files from /var/www/html//YouPHPTube/ to /var/www/html so that the users do not need to type the "YouPHPTube" in their browser. Is this the problem?

**Comment by VictorLi0213** [comment] 2018-06-04 21:36
I'm sure that I have changed the "None" to "All".

**Comment by DanielnetoDotCom** [comment] 2018-06-04 21:49
Make sure you also moved the .htaccess file . It is a hidden file and you may skiped it

**Comment by VictorLi0213** [comment] 2018-06-04 21:52
Do you mean I need to delete the /var/www/html/.htaccess ? Can you tell me exactly how to do it? Thanks!

**Comment by VictorLi0213** [comment] 2018-06-04 21:54
Oh I'm sorry, you mean move the file.

**Comment by VictorLi0213** [comment] 2018-06-04 21:54
Thank you so much!

**Comment by DanielnetoDotCom** [comment] 2018-06-04 21:55
Is it working?

**Comment by VictorLi0213** [comment] 2018-06-04 22:15
Yeah it is working!
And also, the original folder contains "." and ".." (One dot and two dots). Do I also need to move that? What do they mean? Does the one dot mean the current folder and the two dots mean the previous folder?
Thanks a lot!

**Comment by DanielnetoDotCom** [comment] 2018-06-04 22:21
You can't remove "." and ".."

**Comment by hersche** [comment] 2018-06-04 23:12
> Does the one dot mean the current folder and the two dots mean the previous folder?

yes, just like that. they always "exist" :)

i close the issue since you ( @VictorLi0213 ) confirmed it's working thanks to daniels help..

**Closed by hersche** 2018-06-04 23:12 UTC

**Comment by VictorLi0213** [comment] 2018-06-04 23:30
Thank you very much!

**Comment by VictorLi0213** [comment] 2018-06-04 23:31
Hi Daniel, do you use skype? I have many other questions that I want to ask you about. Can we talk more on skype? Thanks a lot!

**Comment by hersche** [comment] 2018-06-04 23:41
the official way is usualy his e-mail ("forked" from other issues :p) developer@youphptube.com

if you want, you can also ask here and reopen it for your questions, and close it when you feel to, i don't want to stress ;)

**Comment by VictorLi0213** [comment] 2018-06-04 23:46
Ok thanks. Here is another problem when I was installing the stream server:

If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:.
State or Province Name (full name) [Some-State]:.
Locality Name (eg, city) []:.
Organization Name (eg, company) [Internet Widgits Pty Ltd]:.
Organizational Unit Name (eg, section) []:.
Common Name (e.g. server FQDN or YOUR name) []:.
Email Address []:.
error, no objects specified in config file
problems making Certificate Request

What should I do?
Thanks!

**Comment by hersche** [comment] 2018-06-04 23:53
this is on create a SSL-certificate as it looks?

do you try to set the current folder for those or why it's a . only?

one solution: use the right values (or use other valid values)

other solution: https://letsencrypt.org/getting-started/
there's a app called "**certbot**".. this works very automatic, the certificate is autogenerated and signed, doing also apache-config and you have to enter almost no information like this above.
