### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#675] opened 2018-05-11 11:42 UTC
Hi Daniel,
Today i face some issue  i install new server ubutnu 16.04 after install youphptube complete go home page  but showing error check below details.

This page isn’t working
 is currently unable to handle this request.
HTTP ERROR 500

**Comment by louisyssel** [comment] 2018-05-11 16:01
Hi,

I just did a complete clean install on Centos 7 with PHP 7.2 and HTTPD, and I am also getting the Eroor 500 after I completed the Installation, and the system states to delete the INSTALL folder, and then I get the error 500.

I would appreciate the help.

**Comment by DanielnetoDotCom** [comment] 2018-05-11 19:56
can you please check the log file?
apache error log and youphptube erro log

**Comment by hersche** [comment] 2018-05-12 02:58
can you both try a update and new install? i think we solved it..

**Comment by gujarraju** [comment] 2018-05-12 07:59
Now working fine.

**Comment by louisyssel** [comment] 2018-05-12 08:27
Hi, yes, it is working for me as well.

Unfortunately, I am installing the encoder as per your video on the main page, and when I entered all the configuration information, the browser is stuck on "Processing". I cheked the issues list under the Endoer lib, but I am not using docker. I am using a clean Centos 7 machine with php 7.2.5 and httpd 2.4.

Any idea what this could be?

**Comment by DanielnetoDotCom** [comment] 2018-05-12 11:42
@louisyssel can you please check your encoder log file?

**Comment by louisyssel** [comment] 2018-05-14 08:43
It does not reach the point to creat e the log file, and the httpd log files shows no errors.

**Comment by DanielnetoDotCom** [comment] 2018-05-14 10:48
it needs to rise some error. with out it we cant help.

**Comment by hersche** [comment] 2018-05-14 15:18
@louisyssel is your installation online? if yes, can you give a url?

if you know how, open the browser's developer console, go to network, on stuck, look to the content of the last requestet file - and paste this here.

**Comment by louisyssel** [comment] 2018-05-14 19:06
Yes, it is online.

http://video.uc-x.net/YouPHPTube/
http://video.uc-x.net/YouPHPTube-Encoder/

Let me know if you need the SSH credentials as well.

Louis

**Comment by hersche** [comment] 2018-05-14 20:14
i can not connect to the server.

the domain-name resolves a ip, but i become no ping-answer from the ip. i've tried with my connection from switzerland and from my server in germany.. don't know if daniel can reach it. or do you power off the server sometimes? not really, i think?

**Comment by hersche** [comment] 2018-05-14 20:46
@louisyssel i tried to reproduce the issue local.

out of mistake, i was on https://encoder-url, while i inputed http://streamer-url.

mix of ssl/non-ssl leads to a infinite progress-bar as well. if you do so, decide between one of them.

**Comment by hersche** [comment] 2018-05-14 20:51
now i can connect to your server.

from the site:
`<script src="/var/www/html/YouPHPTube-Encoder/view/js/jquery-3.2.0.min.js" type="text/javascript"></script>`

/var/www/html/YouPHPTube-Encoder/ is wrong! can not work.

if you want, you can give me access, and i can do it.. or paste your config-file and i can correct the path-part..

**Comment by louisyssel** [comment] 2018-05-15 07:03
I sent the detail, Thank you so much!!!

**Comment by louisyssel** [comment] 2018-05-15 07:47
There is a LetsEncrypt cert on the machine, so if possible, please use HTTPS

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hersche** [comment] 2018-05-15 23:00
can you send me the path to the ssl-certificate?

i do not find it. the rest is working..

**Comment by hersche** [comment] 2018-05-21 17:37
@louisyssel can you confirm it's working for you also? i did not hear anything from you since i did the install..

**Comment by hersche** [comment] 2018-05-24 00:32
i have become a mail that it's working for him.. i think we can close this issue.

**Comment by hersche** [comment] 2018-06-03 12:35
no more feedback, solved, closed..

**Closed by hersche** 2018-06-03 12:35 UTC

**Comment by WGtechy** [comment] 2020-05-22 09:00
> Hi, yes, it is working for me as well.
> 
> Unfortunately, I am installing the encoder as per your video on the main page, and when I entered all the configuration information, the browser is stuck on "Processing". I cheked the issues list under the Endoer lib, but I am not using docker. I am using a clean Centos 7 machine with php 7.2.5 and httpd 2.4.
> 
> Any idea what this could be?

Hello, Please i am having the same issue right now. I need assistance

**Comment by WGtechy** [comment] 2020-05-22 09:01
> no more feedback, solved, closed..

Hello hersche, Please, how can i solve my own issue

**Comment by DanielnetoDotCom** [comment] 2020-05-23 10:46
@WGtechy please open a new issue and provide your details

**Comment by WGtechy** [comment] 2020-05-27 19:15
> @WGtechy please open a new issue and provide your details

This has already been solved
