### ISSUE TITLE
Embed video link doesn't work anymore ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#506] opened 2018-03-22 15:40 UTC
I tried to embed a link from youtube, but even if I save ... the popup does not change (always remains in the foreground ...  this also happens in the demo of your site).
I take the opportunity to ask if is possible that you can do a modify off this embed plug , with modalities that you can also incorporate the iframe codes of the other players so you can also create with the help of the "Top Menu" plug a type of menu, which can open embed players with live TV stations ... that offer their iframes to be incorporated anywhere , also on this site ....

Another thing .. with the latest changes ... I noticed that trying to make changes to the description of the video downloaded from YT ... there are some cases in which if you set the Gallery in the home page ... the texts in the description is doubled ...

Thank you.

**Comment by DanielnetoDotCom** [comment] 2018-03-22 16:00
Yeah, I sent a fix for this this morning, please update your files

**Comment by DanielnetoDotCom** [comment] 2018-03-22 16:01
about the description is doubled, can you please screen shot one for me?

**Comment by tgd1973** [comment] 2018-03-22 16:08
Can you tell me at which address can I send an e-mail?

**Comment by DanielnetoDotCom** [comment] 2018-03-22 16:13
Please, paste the screenshot here or send it to developer@youphptube.com

**Comment by tgd1973** [comment] 2018-03-22 16:40
Message sent. 
If I can make a suggestion ... It would be even more interesting if you could choose ... one or more videos (as administrator) to display them on the home page as freatured, and later to present the gallery ... with the latest videos uploaded ... I saw this option on multiple platforms ... Clipshare, ClipBucket ...

**Comment by DanielnetoDotCom** [comment] 2018-03-22 17:19
check the preferred videos (Star), to display as a main video

![image](https://user-images.githubusercontent.com/18009293/37786599-d94cd1ec-2ddb-11e8-9c05-baa27c3d864d.png)

Can you reproduce the double description on demo site? I could not reproduce it

About the title it will be remover on the future

**Comment by mj1985** [comment] 2018-03-23 09:18
@DanielnetoDotCom you can check the problem with the double description on the demo, too: https://demo.youphptube.com/ ;-) The featured video at top

**Comment by DanielnetoDotCom** [comment] 2018-03-23 11:09
@mj1985 Sorry you right
It is fixed, please update your files

**Comment by tgd1973** [comment] 2018-03-23 15:06
Is there a possibility to make a player at the top of the Gallery plugin that shows freatured videos? (as encircled in the images above)?

**Comment by tgd1973** [comment] 2018-03-23 16:00
From me there are still problems ... I deleted the whole directory apart videos ... result is here down ...

![doublled description in home page - gallery](https://user-images.githubusercontent.com/15127860/37839778-9ad8c0ac-2ebb-11e8-89c8-dc900f329aaa.jpg)

**Comment by DanielnetoDotCom** [comment] 2018-03-24 11:05
Hi, @tgd1973  you said you update and got an error?

Are you sure you update all files?
Also I, please clear your browser cache, because there is also javascript updates on it.

**Comment by tgd1973** [comment] 2018-03-27 07:50
Hi! | As I said I deleted the whole directory, apart from the directory videos ... and the problems have not changed ... Maybe because I do everything in a shared hosting ... that has as Apache webserver but has (to improve the quality) a reverse proxy like Nginx ... all installed as a manual (VestaCP) the curious thing is that up to this update everything worked without any problem ...

**Comment by DanielnetoDotCom** [comment] 2018-03-27 12:28
Just make sure you delete the cache dir on videos directory

**Comment by hersche** [comment] 2018-06-14 00:53
> $global['webSiteRootURL']; ?>img/video-placeholder.png"

this works because of redirection. it's in views-folder.

i close the issue because of inactivity, if the problem persist, reopen.

**Closed by hersche** 2018-06-14 00:53 UTC

**Comment by heme007** [comment] 2019-06-30 05:38
Olá tudo bem. Testou montando um streaming para a minha escola de cabeleireiros, minhas aulas teóricas serão online e encontrei o script do YouPhptube que é incrível, mais também não consegui embutir o vídeo,  ele da o erro 404 not found, onde estou errando?

**Comment by heme007** [comment] 2019-06-30 05:40
![F2D4AD20-88BF-436F-93BC-4EF95E4533AF](https://user-images.githubusercontent.com/49640083/60392750-5d4a1a00-9ae0-11e9-8af5-b6b52b7d04aa.png)

**Comment by DanielnetoDotCom** [comment] 2019-06-30 22:18
Você está tentando compartilhar um endereço interno de sua rede.

este endereço funciona somente em sua escola, não vai funcionar na internet.

**Comment by heme007** [comment] 2019-07-01 15:32
Na verdade meu YouPHPTube esta em uma vps da locaweb na internet.
http://191.252.196.168/YouPHPTube/

Eu tento fazer embed mais da erro 404, o quando eu coloco o endereço ele aparece o link
________________________________
De: YouPHPTube <notifications@github.com>
Enviado: domingo, 30 de junho de 2019 22:18
Para: YouPHPTube/YouPHPTube
Cc: heme007; Comment
Assunto: Re: [YouPHPTube/YouPHPTube] Embed video link doesn't work anymore ... (#506)


Você está tentando compartilhar um endereço interno de sua rede.

este endereço funciona somente em sua escola, não vai funcionar na internet.

**Comment by DanielnetoDotCom** [comment] 2019-07-01 20:53
Olá

na verdade seu link parece OK

http://191.252.196.168/YouPHPTube/videoEmbed/historia

não consegui  ver o erro 404

Onde vc viu o erro 404?

**Comment by heme007** [comment] 2019-07-03 03:44
Eu tenho uma rede social de script humhub, e quando eu coloco o link ele não abre, da erro 404.
Na tela de configuração de Oembed ele pede pra colocar endereço json como esse: http://www.youtube.com/oembed?scheme=https&url=%url%&format=json&maxwidth=450

Eu consigo isso no youphptube?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: YouPHPTube <notifications@github.com>
Enviado: Monday, July 1, 2019 5:53:29 PM
Para: YouPHPTube/YouPHPTube
Cc: heme007; Comment
Assunto: Re: [YouPHPTube/YouPHPTube] Embed video link doesn't work anymore ... (#506)


Olá

na verdade seu link parece OK

http://191.252.196.168/YouPHPTube/videoEmbed/historia

não consegui ver o erro 404

Onde vc viu o erro 404?

**Comment by heme007** [comment] 2019-07-04 04:04
Eu tentei colar o link de embed:
<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="http://191.252.196.168/YouPHPTube/videoEmbed/historia" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>


Mais não funcionou, o que estou fazendo de errado?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Hemerson Somah
Enviado: Wednesday, July 3, 2019 12:44:04 AM
Para: YouPHPTube/YouPHPTube; YouPHPTube/YouPHPTube
Cc: Comment
Assunto: Re: [YouPHPTube/YouPHPTube] Embed video link doesn't work anymore ... (#506)

Eu tenho uma rede social de script humhub, e quando eu coloco o link ele não abre, da erro 404.
Na tela de configuração de Oembed ele pede pra colocar endereço json como esse: http://www.youtube.com/oembed?scheme=https&url=%url%&format=json&maxwidth=450

Eu consigo isso no youphptube?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: YouPHPTube <notifications@github.com>
Enviado: Monday, July 1, 2019 5:53:29 PM
Para: YouPHPTube/YouPHPTube
Cc: heme007; Comment
Assunto: Re: [YouPHPTube/YouPHPTube] Embed video link doesn't work anymore ... (#506)


Olá

na verdade seu link parece OK

http://191.252.196.168/YouPHPTube/videoEmbed/historia

não consegui ver o erro 404

Onde vc viu o erro 404?

**Comment by DanielnetoDotCom** [comment] 2019-07-05 12:53
Por enquanto não temos suporte oembed
