### ISSUE TITLE
Remote File storage Request

### ISSUE THREAD

**Issue by woshka** [DanielnetoDotCom/YouPHPTube#669] opened 2018-05-10 22:30 UTC
Hello,

I need to have my main website on first-domain.com
and the files on a remote server second-domain.com
all script files and databases will be on the first-domain.com and the static video files and the converter on the remote server with second-domain.com
Let me know How much this feature request costs

Thanks

**Comment by DanielnetoDotCom** [comment] 2018-05-11 11:44
Hi, you may looking for an S3 Support.
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Use-AWS-S3-on-YouPHPTube

There is a plugin to support S3 storage.

**Comment by woshka** [comment] 2018-05-11 18:00
I don't want to use Amazan
I want to use my own server but it is located elsewhere
How To achieve this

Thanks

**Comment by DanielnetoDotCom** [comment] 2018-05-11 19:48
if you can map your server on the streamer server and create a symbolic link as the videos directory it may work for you

**Comment by woshka** [comment] 2018-05-11 21:52
I want the files to be uploaded to the external server and converted there
the files locations on the external server
is it possible this way?

**Comment by hersche** [comment] 2018-05-14 16:05
i can think about a solution, where the encoder-part is on a own server (as usual), but sends then only the link to the video, saved on the encoder's server.

this would need changes in streamer's and encoder's core. you already asked, how much it would cost - a point there: do you mind when it's released open source (but still commercial)? because it's more difficult to update modified core, it would be more easy, when it's open..

i think i can do those changes, if you're interessted, you can email me at vinzenz.hersche@gmail.com
(if daniel is interessted in doing this, he knows my contact ;) )

**Comment by hersche** [comment] 2018-06-07 12:34
hey, since a while, there is a solution called linkVideo.

go to my videos, "embed video"-button and select the mp4-link there.

you need to do this manualy then, but it is basicly easy possible to have videos on onedomain.org and the streamer on theotherdomain.org . at least if you have direct access to the file and respect that both sites are using ssl (or none, no mix).

i assume this solves your problem only partially, but like said, for the rest, someone can hire me.

**Comment by hersche** [comment] 2018-06-07 20:56
and i just reconized that this is kind of duplicate of  #724

if you both send me a mail, we can link it together, so both of you have to pay a bit less (divided by 2)

**Closed** 2019-02-21 18:25 UTC
Labels: wontfix
